default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: permis_master_development
  username: niels
  password: lolman43
  host: localhost
  port: 5432

test:
  <<: *default
  database: permis_master_test

production:
  <<: *default
  database: permis_master_production
  username: permis_master
  password: <%= ENV["PERMIS_MASTER_DATABASE_PASSWORD"] %>
