default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: permis_master_development
  username: niels
  password: lolman43
  host: localhost
  port: 5432

test:
  <<: *default
  database: permis_master_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || "postgres://permis_master:#{ENV['PERMIS_MASTER_DATABASE_PASSWORD']}@your-production-host:5432/permis_master_production" %>
