default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: permis_master_development
  username: niels
  password: lolman43
  host: localhost
  port: 5432

test:
  <<: *default
  database: permis_master_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-clq3ffie9h4c73ahpqig-a.oregon-postgres.render.com
  port: 5432
  database: permis_master_development
  username: permis_master_development_user
  password: jBz8ipeCLgFea3uXSZDbsWyPNQPaxGWi
