default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: permis_master_development
  username: permis_master_development_user
  password: jBz8ipeCLgFea3uXSZDbsWyPNQPaxGWi
  host: dpg-clq3ffie9h4c73ahpqig-a
  port: 5432

test:
  <<: *default
  database: permis_master_test

production:
  <<: *default
  database: permis_master_production
  username: permis_master
  password: <%= ENV["PERMIS_MASTER_DATABASE_PASSWORD"] %>
